### ISSUE TITLE
Import SVG files

### ISSUE THREAD

**Issue by millervsr** [nkallen/plasticity#46]
As a designer who has limited 3D experience, it would be wonderful to be able to import SVG files that I generate in Adobe Illustrator. This would allow me to quickly generate models from specific forms. Thanks for creating this wonderful tool!

**Comment by kaseopea** [comment]
+1

**Comment by LanceGlasgow** [comment]
That's why I'm here as well - This workflow could become incredibly powerful for many using Inkscape, Illustrator, Affinity Designer and many more dedicated vector drawing softwares. This is especially true thanks to the easy to use tooling within Plasticity, and that typography and custom vector shapes can easily be converted or exported to SVG.

**Comment by gunnerfred** [comment]
Oh yes, this would be a big reason for me for working with Plasticity to help me create FBX extrudes for Adobe Dimension (from shapes I export from Illustrator).
