### ISSUE TITLE
Incorrect copyright notices

### ISSUE THREAD

**Issue by jvanstraten** [nkallen/plasticity#56]
@nkallen, do with this what you will, but the current copyright notices, for as far as they exist, are *far* more permissive than you intend them to be. Not only is this clearly causing confusion (#53, #30), but I seriously doubt your

> You ABSOLUTELY do not have permission to redistribute binaries

at https://github.com/nkallen/plasticity/issues/30#issuecomment-1060933725 would hold up in court when the repo root clearly states LGPL, and `/usr/share/doc/plasticity/copyright` (in the 0.5.32 .deb release anyway) actually states:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software [as long as this notice is retained].

because apparently the Electron license ended up in the place where any reasonable person looking for a license might expect to find it.

Note also that your comment probably would not take precedence over the one contained in the release. Open source licenses are not revocable, because they'd be worthless to users if that were the case. Imagine if Linus Torvalds would be allowed to change his mind about the license of the Linux kernel; that would instantly make basically every smart device in the world illegal to manufacture, sell, or use without a license explicitly stating otherwise.

I know normal people hate dealing with licenses and other forms of legalese, but you should really fix this if you're really serious about making money off of this project down the line. As stated, you can't really revoke these licenses for anyone who's already downloaded any of the existing releases, but you *can* fix it for newer releases. I would:

 - add a header to the copyright file in the releases stating that Plasticity is all rights reserved by you, followed by that it uses Electron, for which the license is [whatever is currently in the file];
 - add a header to `LICENSE` stating the same thing, followed by that the sources in this repository are licensed using the LGPL; and
 - clarify your intentions in `README.md`.

License text that may or may not hold up on court because it wasn't written and checked by a horde of lawyers is still better than license text that explicitly allows people to basically do whatever they want with it, when that is clearly not your intention. Those 5-10 minutes of work may save you a lot of trouble down the line.

Disclaimer: I am not anyone's lawyer, and this should not be construed as official legal advice in any capacity. I only have a random interest in copyright law for some reason, but I'm not schooled in it by any means. Talk to a real lawyer if you want to be sure.

Edit: grammar

**Comment by nkallen** [comment]
Thanks - I appreciate this advice and I'll follow it. I cannot allow people to redistribute the binary. My source code is a different issue.

**Comment by nkallen** [comment]
Just for some context -- I want as much as possible of the code I write to be open source, so users can modify the app and/or write plugins. But because I license a commercial library, I have legal obligations.

**Comment by nkallen** [comment]
I've asked in the electron discord on how to change /usr/share/doc/plasticity/copyright

It doesn't seem configurable at all

**Comment by lodenrogue** [comment]
What is the main issue with the closed source binary? Is it a binary you own and control and are choosing not to open source it or is it a third party proprietary library you're dependent on?

**Comment by jvanstraten** [comment]
@lodenrogue Quoting the new/current readme:

> HOWEVER, it dynamically links with a commercial software software that I have licensed for $$$$$$$$. That license imposes many restrictions on how the app can be distributed and what functionality is available to end users. Please do not redistribute the binary.

I also thought it was that they just wanted to keep part of their app closed-source first, but clearly there's a commercial dependency involved.

**Comment by nkallen** [comment]
Yeah for those of you unfamiliar, nearly all CAD programs use a kind of library called a "geometry kernel". There is an open source geometry kernel called OpenCascade and there are a small handful of commercial options. In general it takes decades to write a Geometry Kernel. The current state of the world is such that the commercial options are much more feature-rich than the open source options.

**Comment by jvanstraten** [comment]
I'm guessing this is why FreeCAD can't do half of the operations I want it to do and segfaults every other operation for the remainder? Kind of off-topic, but this is what drew me to this project; I'd love an affordable CAD-like tool that runs on Linux, to complement Blender's mesh-based modelling. FreeCAD just flat out broke every time I gave it a chance, and the more mainstream tools either can't do basically anything, cost an unjustifiable amount for designing the occasional simple 3D print model, and/or don't run (natively) on Linux. Timelines and constraints would be great, but I don't think Plasticity is going in that direction (?), and I can live without, considering I use Blender currently.

**Comment by nkallen** [comment]
FreeCAD/opencascade is wonderful but the reality of geometry kernel development is:

super complicated math * an insane number special case handling = a good kernel

I am optimistic FreeCAD/OpenCascade will be amazing some day, but it's going to take years

**Comment by lodenrogue** [comment]
Thank you for this explanation

**Comment by UglinessInTheUI** [comment]
FreeCAD already exports clean meshes without any artifacts but it's still not doing it as full quads. It has plenty of triangles even if you prioritize the mesh as quads. At the moment I'm getting way more artifacts and duplicated edges and broken faces from Plasticity compared to FreeCAD. I think Nick should remake the software based on FreeCAD code and forget about those restrictive licenses. Nobody wants to deal with broken programs full of restrictions and that never compile from source code.

**Comment by nkallen** [comment]
OBJ export in plasticity is just an experimental feature, and will improve over time. Like many things, it's a rough first implementation while I work on every aspect of the app. I am frustrated when people come to me and don't understand what beta software is, despite my having warnings everywhere about it.

I can tell you WITH CERTAINTY that FreeCAD is about 100x buggier than c3d and extremely limited in its fillet and direct modeling capabilities. I am evaluating Parasolid, which is the best kernel available, but it is also more expensive. There is no world in which using FreeCAD is an option if I don't want plasticity to be just a toy.

**Comment by UglinessInTheUI** [comment]
I think I had the wrong settings in the Blender OBJ Importer. It works a little better if you don't select the Geometry Split option. Just use the other option that says Keep Vert Order + Poly Groups. Anyway, I still don't know how to convert the mesh to quads 100%. ALT+J is doing it but only in some areas. Other areas still have triangles. Here is a video I made while I was testing it. Sometimes the boolean union works and other times the object gets cleared without doing the union. 

https://youtu.be/2CdqSLDIJZI

**Comment by nkallen** [comment]
There is no automated way to get all quads from breps. You can use use a remeshing tool, something like QuadRemesher, or look at libigl if you're curious how the math works or read some recent research e.g., https://www.quadmesh.cloud

**Comment by UglinessInTheUI** [comment]
QUADWILD looks good but there is no compiled windows binary. I tried the JRemesh for Blender but seems to be broken. It generates lots of holes in the mesh even when the fill option is checked. https://github.com/jayanam/jremesh-tools

I also tried MeshLab but it has the same problem like JRemesh.

**Comment by eGit** [comment]
C3D is very solid. Some bugs, but same for Parasolid in some areas. From a technical standpoint I don't see how switching to Parasolid makes a lot of sense especially since you already have C3D working pretty well. Maybe C3D would even give you the sources (obviously with a non-publish clause), so you could iron out all the bugs you see down the road. 

I doubt you will get a C3D source snapshot but at least there is a 1 in a 100 chance. Parasolid won't give you nothing ever ;)

Btw, could you use some of the functionality of FreeCad/OpenCascade (I have zero experience with them) and just the special stuff from C3D? Maybe you could get that small functionality as source from C3D.

**Comment by nkallen** [comment]
Each geometry kernels has an internal representation of the BREP data structure that is not mutually intelligible without some sort of export/import process, which is way too slow to do any real mixed kernel stuff like you're proposing.

All kernels have bugs because BREPs are basically a nightmare. Do you have direct experience with Parasolid? I'm currently doing an evaluation and if you do have such experience I'd like to get in touch. I've been in touch with a few users of OpenCascade and one other parasolid user and I want as much info as possible.

**Comment by eGit** [comment]
Only second hand info since a colleague coming from C3D worked with Parasolid. I remember him complaining that it wasn't better then C3D. Maybe that has changed by now.

Why would you switch from C3D?

**Comment by UglinessInTheUI** [comment]
You should implement all the functions you want using Blender Geometry Nodes. You can probably do everything you want using those new nodes. After that you can translate everything to a new program and make it easier to use or more convenient and have something that you can sell without any closed source restrictions. I would stay away from Parasolid.

**Comment by eGit** [comment]
> You should implement all the functions you want using Blender Geometry Nodes. You can probably do everything you want using those new nodes. After that you can translate everything to a new program and make it easier to use or more convenient and have something that you can sell without any closed source restrictions. I would stay away from Parasolid.

Is this just a wild guess or is this statement born in actual experience. I don't know much about Blender Geometry Nodes. I know they are very powerful but aren't you comparing apples to oranges? Are Blender Geometry Nodes even close to anything what a "geometry kernel" does?

Can you give a example where you implement simple functionality of an geometry kernel with Blender Geometry Nodes? Or is this just a wild, unfounded guess on your part?

"Geometry kernel", "Blender Geometry Nodes". Well, they both have "geometry" in their names, so they probably do the same. Can't be much different. Just do it. Piece of cake :(

**Comment by nkallen** [comment]
@eGit 

1. This guy has absolutely no idea what he's talking about please do not waste your energy talking with him

2. Can you put me in touch with your friend who has used both c3d and parasolid?

There are various reasons I'm looking into Parasolid. One of them is that it has more powerful direct modeling, including the ability to rotate faces that are connected by fillets to adjacent faces, arbitrary face transformations (like twist), and so forth. My assumption is that parasolid has fewer bugs because it more mature, already stressed by users of Solidworks and shapr3d for instance. It's really difficult to know the defect rate of a kernel without working with it full time for 6 months.

**Comment by jvanstraten** [comment]
> I don't know much about Blender Geometry Nodes. I know they are very powerful but aren't you comparing apples to oranges? Are Blender Geometry Nodes even close to anything what a "geometry kernel" does?

Blender is mesh-based, not surface/solid-based. If you were to simplify it down to 2 dimensions, the mesh-based approach only supports line segments (the 3D equivalent being polygons), while the surface/solid approach supports curves, arcs, and so on in addition to those straight line segments. The mesh-based approach can only approximate those things, but because the algorithms are comparatively simple, it can handle orders of magnitudes more primitives before it slows down noticeably.

When you're into computer graphics or anything related to that, mesh-based will probably work better for you. The renderers ultimately convert everything to triangles anyway (or in Blender's case maybe arbitrary polygons nowadays, even deep down in the guts of Cycles), and a million vertices give you a lot more creative freedom than a hundred surfaces. When you're working on a model that's going to be manufactured on a lathe or mill however, software that can't perfectly represent the basic shape you're working with, being cylinders, is all but completely useless. No amount of vertices will ever change that.

Plasticity seems to be trying to bridge the gap between surface-based design for CAD and computer graphics. Which I think is great, because the surface-based flow has a lot of perks to it compared to Blender. I mean, try poking a cylindrical hole into a complicated mesh and have a look at what the boolean geometry node spits out. Forget about quads (hint, they'll be N-gons, and very ugly ones at that); you'll be lucky if it's still manifold. It *sucks*, but that's just the nature of the algorithm for mesh-based boolean ops (it's very numerically unstable, and floating point values are far from perfect). For surface-based stuff this is one of the most primitive operators; it's designed specifically to do this well and without any amount of error, at the cost of not supporting completely free-form geometry, or not supporting it as well anyway.

UglinessInTheUI: as a developer myself, it's extremely demotivating to have someone inform you that what you're doing is basically worthless and stupid just because it doesn't tick all the boxes of their particular workflow. I can only imagine what it's like when, in addition to lots of your time, you've already invested a probably not insignificant amount of your own money to give your software out for free to the internet, only for someone to tell you it's not free enough for them and not useful anyway unless they start completely from scratch, because make no mistakes, that's what you're suggesting. If Plasticity's approach is not your thing, just move on. Nothing that's free will ever beat Blender in open-source mesh-based modelling anyway, and even $$$ commercial stuff is hard-pressed to compete nowadays. Meanwhile, in the CAD world, there is no Blender that does everything just as well for free, there is only "call to request a quote"-level-expensive software for anything that isn't a toy. nkallen is a hero in my book if he pulls this off.

**Comment by eGit** [comment]
> @eGit
> 
> 1. This guy has absolutely no idea what he's talking about please do not waste your energy talking with him
> 2. Can you put me in touch with your friend who has used both c3d and parasolid?
> 
> There are various reasons I'm looking into Parasolid. One of them is that it has more powerful direct modeling, including the ability to rotate faces that are connected by fillets to adjacent faces, arbitrary face transformations (like twist), and so forth. My assumption is that parasolid has fewer bugs because it more mature, already stressed by users of Solidworks and shapr3d for instance. It's really difficult to know the defect rate of a kernel without working with it full time for 6 months.



> @eGit
> 
> 1. This guy has absolutely no idea what he's talking about please do not waste your energy talking with him
> 2. Can you put me in touch with your friend who has used both c3d and parasolid?
> 
> There are various reasons I'm looking into Parasolid. One of them is that it has more powerful direct modeling, including the ability to rotate faces that are connected by fillets to adjacent faces, arbitrary face transformations (like twist), and so forth. My assumption is that parasolid has fewer bugs because it more mature, already stressed by users of Solidworks and shapr3d for instance. It's really difficult to know the defect rate of a kernel without working with it full time for 6 months.


He wasn't my friend, just a colleague I talked to a few times - don't even know his full name. I will try to get his contact info. Aren't there forums for C3D or Parasolid?

More functionality seems better, but the question is, is this additional functionality of Parasolid really a game changer for most users? Or is it something only 1% of power users would like to have but also only use once in a while? Blender is a good example where a slimmer approach would benefit 99.9% of people. The way you do modelling is very "indirect". It almost feels like Excel working with Modifiers for example. You apply it to the right in the Properties-View. Then you have a myriad of options but they are often not intuitive. Your eyes and mouse always move between the Viewport and the Properties. People even developed add-ons to make this much better: https://pitiwazou.gumroad.com/l/speedflow

What I am trying to say, is, maybe stick with C3D (which already works very well it seems) and focus on polishing the workflow (which has nothing to do with the geometry kernel). The UI, etc. (which is already very good). 99.99% of users want easy, clean UI with a set of basic functionality (which from my first test of Plasticity) seems to be there. Actually there is already more advanced stuff then most people will ever need. From my experience many users skip even most of the basic stuff like mirror or array and do it manually since it is faster for them.

IMHO better build a tool that 100k+ people want to use that will attract genius add-on developers who will add niche functionality instead of building something that has a maximum of features but which 1k+ people want to use.

The question is, if you don't switch to Parasolid now and in two years you discover that for whatever reason you will have to. Will it be 10x harder then switching now? Or will it be more or less the same time investment?

**Comment by UglinessInTheUI** [comment]
I never said it's worthless. Where did I say that ? Plasticity is already pretty good, if you ignore the bugs and that annoying pop-up window that is constantly interfering with the 3D view, I just don't see Parasolid as a good idea at all. The solid part is also pretty annoying when you are not able to pull on any of it's vertices and there are no modifiers like Bend, Twist, Taper, Stretch. As far as, Geometry Nodes, there are some advanced tutorials on YouTube and they also support curves which means it should also support surfaces.

**Comment by nkallen** [comment]
@eGit I appreciate your point of view. It's definitely a viewpoint I can sympathize with and I personally would rather much rather sell a lot more for a smaller price. With Parasolid it's hard to imagine being able to sell for less than $150 (although perhaps there would be a free demo and cheaper "noncommercial" tier). $150 is professional software, it's a world away from $25. I never hesitate to buy $25 programs but I rarely buy $150 programs unless I am totally convinced I need it.

The thing that pushed me to look into Parasolid initially was my bank refusing to send money to Russia to pay c3d. Around the same time, my bug backlog with c3d briefly topped 70 open tickets, including quite a few open still open from October/November. Simultaneously, one of my most engaged beta testers, who was building an amazing sci fi helmet, gave up because the kernel was no longer able to mirror it. At this point I started wondering if the kernel's defect rate was too high for me to ship. Sure, for $25, who cares I guess? But I do care. If nothing else, it's actually a lot of work for me to investigate the bug reports, determine if it is or isn't my code, then shepherd the bug with c3d.

I'm attaching a picture, just an example of something parasolid can do that c3d can't. c3d will build this feature someday but I doubt it will happen this year.

<img width="763" alt="Screenshot 2022-04-04 at 00 38 13" src="https://user-images.githubusercontent.com/699/161451767-4a970f5c-e8ff-48f4-906e-ce81ac9af7b0.png">

This is the analog of scaling an edge in polygons. Is it an advanced/obscure feature? I don't think so, personally, but it isn't absolutely vital to the app being useful. It's something I want to use. Professionals? Yes. Average people - maybe?

Currently my biggest unknown is what is the Parasolid defect rate is. I've talked to a Shapr3D employee who also used OpenCascade. They're very very very happy to use Parasolid. But I can't directly compare that to c3d.

**Comment by UglinessInTheUI** [comment]
Geometry Nodes is like building your own Plasticity modeler from scratch using visual programming or node graphs. It probably has some limitations that I don't know about but it's trying to be more like SideFX Houdini and not Solidworks. Here is one beginner tutorial.

https://www.youtube.com/watch?v=4WAxMI1QJMQ

**Comment by eGit** [comment]
You are quite in a tough spot. I assume using C3D is far from perfect but who knows how the Parasolid experience will be down the road. It's probably also not feasible to use C3D for a low-cost solid but small-feature version and Parasolid for the full-featured package? Like make a first C3D release with a polished small feature set and grow a user base while working on a fully-fledged version with Parasolid which motivates some of the C3D users to migrate? And if Parasolid doesn't pan out as expected and/or C3D steps up its game you could still go 100% C3D. From my experience it is always best to release something usable quickly (~ 6 more months), get a real user base,etc. and take it from there.
There are always bugs in extremely complex projects and maybe even Parasolid has its limits where you need to split up an extremely complex project into several smaller parts.

What do you think is a realistic time-frame to get to the point you are now with C3D when switching to Parasolid? When would you be able to make your first Parasolid release?

**Comment by UglinessInTheUI** [comment]
Feedback what is most important to them ? Using what ? Guilty ass Discord ? I don't think so. Go check first what is Discord guilty of before you make such illegal recommendations in my bedroom. You are still subject to my bedroom laws even if you don't know it yet. Nick is going to need a support page that is not from guilty ass Discord. Because Discord is just too fucking corrupted and guilty of way too many scams. And nobody has tolerance for scams at this time.

**Comment by nkallen** [comment]
I just deleted that users comments. Some people are such a nuisance. The combination of complete ignorance and incredibly strongly held opinions that I find to be such a charming combination.

Anyway.

I think a Parasolid port is 2 months of effort. It's hard to know with certainty, but I started the evaluation two weeks ago and I have a fork of plasticity with the ability to create simple primitives, and fillet edges interactively, and facet bodies for gpu rendering. It's not easy exactly, but it gives a sample of the effort involved. There are still many unknown unknowns. A Parasolid port will still allow me to release this year. But it's a 2-3 month delay. September which was my original goal seems unlikely.

**Comment by eGit** [comment]
![2-3](https://user-images.githubusercontent.com/842855/161508310-64e1fc14-aa9f-41f1-9152-026aeeb54e60.jpg)

Well, then you maybe even want to have two versions of Plasticity. The lean, affordable version with C3D and the feature-complete version with Parasolid. I would side with releasing the C3D version as fast as possible and then fully focus on the Parasolid port.

**Comment by nkallen** [comment]
I'll think about it. Part of the migration process would involve a version of plasticity that is probably 80-90% compatible with both kernels. I can't say for sure how difficult a 100% "modular" kernel architecture would be, but that's not what worries me. I think it might be a long-term maintenance nightmare. Obviously I do a lot of unit testing, but this would mean the manual QA I do would have to be repeated for each kernel. I have to field support from users with two significantly different versions of the app. So it's not the initial effort that scares me, but the ongoing maintenance.

**Comment by jvanstraten** [comment]
I'm a pretty pessimistic person, but I wouldn't bet on the sanctions on Russia going away anytime soon. If I were you I'd stash what you have now somewhere, and switch to the less politically-sensitive option if it "only" takes a few months to do so. Focus on that first, keeping your internal interfaces with the backend clean so you don't have to start over completely if the situation changes and/or you change your mind (or if someone else wants a shot at replacing it with an open-source backend). Just my two cents.

By the way, feel free to close this issue whenever you feel like you've dealt with the license stuff. It was just meant to be a heads-up, and the discussion has gone more than a bit off-topic. Might be better to just open a separate issue for this, so it's easier to find.

**Comment by nkallen** [comment]
Yeah sorry I apologize for being so off topic.

This subject is literally all I think about right now

**Comment by eGit** [comment]
What do the sanctions have to do with software development? I never stopped doing business with the US and their allies during Irak1, 2, Lybia, Syria, Yemen, etc. - why should I stop doing business now with Russians that have even less say in the course of their country then US citizens? I refuse to be a US-Phobe or Russiaphobe for that matter.

I don't see why this should influence anything. If there are technical reasons against C3D sure. But not this geopolitical bs. You are shooting yourself in the foot if you don't release a $25 app with C3D and build a user base first. If you go directly for $150 with Parasolid your chances of success are probably very very slim. That's just my experience after 20+ years of software development.

**Comment by nkallen** [comment]
Yeah - it's currently difficult/impossible for me to directly do business with a Russian company. However, they are in the process of opening bank accounts outside of Russia, etc. It'll work out with c3d if I so choose, but it's not a great situation for a lot of reasons

**Comment by eGit** [comment]
Just like with the C19 restrictions it is not very wise to comply with their bs. Rules for me but not for thee. While small children sit 8 hours a day in a classroom with masks, politicians do a 500+ group maskless smiling photo-op in Davos. The US is importing oil from Russia at full speed. Do you notice a pattern? You cannot comply your way out of tyranny.

All you have to do is rake over the licensing fee, now and then, right? Maybe just go back to envelopes and cash.

**Comment by nkallen** [comment]
I know this is off topic but I will say one more comment about price. Most of the available alternatives (Moi3D, Fusion commercial, Shapr3D, etc.) are asking much more than $150, or requiring a subscription, etc. Among my beta testers I have many professionals working in the video game industry and for them $150 is basically nothing. It's also worth comparing prices to Marmoset Toolbag or 3D coat or other niche pipeline tools ($400 ish). I don't think my chances of success are slim at $150, but it's a different market than what I was hoping for. I wanted to get all the people who by HardOps/Boxcutter to buy plasticity, and they aren't going to at $150.

**Comment by shoeoffhead** [comment]
True. But for every professionals there are 100x-1000x hobby makers, 3D printers and designers. If you sell it for $150 you still have to do a free trial period or a demo or something. Most of those hobby people will never download and try it.

If you do a $25 app many people will buy it and then when the $150 improved version comes out 6 months later, a considerable number who wouldn't pay $150 straight up, will switch. You could give a $25 discount for those who bought version 1.0

I don't get it. You already have the C3D version close to finished. It's not like you destroy your chances for the $150 version, which will be much more professional and feature rich. You increase your chances of the $150 becoming a success. Going directly for the $150 version will cost you additional time and money and lower the chances of success.

**Comment by nkallen** [comment]
Listen - I haven't made a decision yet and I'm definitely taking your feedback into account.

But in case you missed it (you said "I don't get it"): I have non-trivial frustrations with c3d, but overall - I wouldn't have started an evaluation of Parasolid if not for the war. I literally can't pay them at the moment. I have two American banks who refuse to wire money to Russia. This is a ridiculous situation for me to be in - I'm just a programmer! I think @eGit above was joking about envelopes of cash but dude I'm not going to deal with envelopes of cash. Plan B is they set up bank accounts in China etc to get around sanctions. You can at least understand why this situation feels risky/potentially catastrophic to me, right? I'm relying on a Russian supplier when Russia is under massive sanctions and potentially going the way of North Korea...

**Comment by shoeoffhead** [comment]
Thanks for clearing that up. I would ignore the fake-crisis propaganda. I get the feeling somebody bombarded you with doom and gloom. Don't let it get the better of you.
Also there is a phenomenon, where developers shortly before they are finished look for a reason to torpedo their own project and start almost from scratch.
