### ISSUE TITLE
Allow specifying length of line

### ISSUE THREAD

**Issue by leon** [nkallen/plasticity#77]
While drawing shapes using the line tool you don't know anything about how long the line is.
I'm using plasticity for simple 3d prints, the work flow is awesome, but this would make it even better :)

## Status Indicator
Show the current line segment length while drawing

## Allow setting the length of the current line segment
Point the line in the axis you want then type the length on the keypad and hit enter to confirm length.

**Comment by Fura123** [comment]
This was a response to a topic with the same question.
''nkallen commented on 6 Mar''('I think I understand what you're asking for but .... But dimensions are not in plasticity because plasticity is a tool for concept artists. Sometimes more analytic concept artists want to work with precise measurements (a gun is exactly 10x3x2 units or whatever). But they don't need to dimension things..'')''

There's no logic, a program is based on measurements and doesn't need measurements because of the "concept artists", everything is done with measurements. If this is logical!! Why do squares have measures to have equal sides? and the fillet? better to do everything by eye, and nothing by measurements. The topic has a lot of logic, measurements are always necessary, even for concept artists.
